plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
    id 'signing'
}

android {
    namespace 'com.authmatech.sdk'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10"
    implementation 'androidx.core:core-ktx:1.10.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'org.json:json:20230227'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

afterEvaluate {
    publishing {
        publications {
            register("authmatech", MavenPublication) {
                if (components.findByName("release") != null) {
                    from components.release
                }

                groupId = 'com.authmatech'
                artifactId = 'authmatech-sdk-android'
                version = '1.0.0'

                pom {
                    name.set("Authmatech Mobile Identity SDK")
                    description.set("Authmatech SDK for Android enables mobile detection over mobile data through mobile network operator (MNO), designed for seamless integration by developers and clients.")
                    url.set("https://github.com/Authmatech/authmatech-sdk-android")
                    licenses {
                        license {
                            name.set("MIT License")
                            url.set("https://opensource.org/licenses/MIT")
                        }
                    }
                    developers {
                        developer {
                            id.set("authmatech-team")
                            name.set("Authmatech Team")
                            email.set("support@authmatech.com")
                        }
                    }
                    scm {
                        url.set("https://github.com/Authmatech/authmatech-sdk-android")
                        connection.set("scm:git:git://github.com/Authmatech/authmatech-sdk-android.git")
                        developerConnection.set("scm:git:ssh://github.com:Authmatech/authmatech-sdk-android.git")
                    }
                }
            }
        }

        repositories {
            maven {
                name = "sonatype"
                url = uri("https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/")
                credentials {
                    username = findProperty("ossrhUsername") ?: System.getenv("OSSRH_USERNAME")
                    password = findProperty("ossrhPassword") ?: System.getenv("OSSRH_PASSWORD")
                }
            }
        }
    }
}



apply from: "$projectDir/ktlint.gradle"

apply plugin: 'signing'

signing {
    useInMemoryPgpKeys(
            findProperty("signing.keyId"),
            findProperty("signing.key"),
            findProperty("signing.password")
    )
    sign publishing.publications.authmatech
}